### ISSUE TITLE
Report Formatting

### ISSUE THREAD

**Issue by ctesta01** [ctesta01/oire-report-generation#4]
The final result will be a docx report with formatting as similar as possible to the current format used. 

The report formatting will divide into roughly two components: the components done in LaTeX and the components done in Word. 

Likely, LaTeX code will mostly correspond to document structure and what will be left to do will be aesthetic changes done in Word.

**Comment by machamer** [comment]
Tex examples thought to be useful: 075-knit-expand, 087-child-example.  

Is there a preview that currently exists that we want to recreate via LaTeX?

**Comment by ctesta01** [comment]
We've moved away from using Word at any time during this project -- instead pandoc will convert to HTML which can be rendered in Excel. 

We'll be working hard on automating formatting in Excel now instead.
